import { ProcessedSocialContent, HashtagMetrics, PlatformMetrics } from './socialDataProcessors';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export interface ExportOptions {
  format: 'csv' | 'json' | 'xlsx' | 'pdf';
  includeCharts?: boolean;
  includeMetadata?: boolean;
  dateRange?: {
    start: string;
    end: string;
  };
  filters?: {
    platforms?: string[];
    sentiment?: string[];
    engagement?: string;
  };
}

export interface ExportData {
  title?: string;
  data?: any[];
  columns?: ExportColumn[];
  content?: ProcessedSocialContent[];
  hashtags?: HashtagMetrics[];
  platforms?: PlatformMetrics[];
  metadata?: {
    exportDate?: string;
    totalRecords: number;
    filters?: any;
    generatedBy?: string;
    section?: string;
    generatedAt?: string;
    searchQuery?: string;
    platform?: string;
    keyword?: string;
  };
}

export interface ExportColumn {
  key: string;
  label: string;
  type: 'string' | 'number' | 'date' | 'url';
  format?: (value: any) => string;
}

export interface ExportFormat {
  format: 'pdf' | 'csv' | 'xls';
  label: string;
}

class ExportService {
  // Get available export options based on data section
  getExportOptions(section: string): ExportFormat[] {
    const baseOptions: ExportFormat[] = [
      { format: 'csv', label: 'CSV Spreadsheet' },
      { format: 'xls', label: 'Excel Workbook' }
    ];

    // Add PDF option for sections that support visual export
    const pdfSupportedSections = [
      'dashboard',
      'reports', 
      'News Blog Monitoring',
      'Dashboard Analytics',
      'Social Listening',
      'Social Listening Finder',
      'Sentiment Analysis',
      'Hashtag Finder API',
      'Keywords Management',
      'YouTube Search',
      'Social Analytics',
      'Competitor Analysis',
      'Hashtag Tracker',
      'Trending Mentions',
      'AI Chatbot'
    ];

    if (pdfSupportedSections.includes(section)) {
      baseOptions.unshift({ format: 'pdf', label: 'PDF Report' });
    }

    return baseOptions;
  }

  // Export data to CSV format
  async exportToCSV(data: ExportData, options?: ExportOptions): Promise<Blob> {
    console.log('📊 exportToCSV called with:', { data, options });
    let csvContent = '';
    
    // Add metadata if requested
    if (options?.includeMetadata && data.metadata) {
      csvContent += `# Export Metadata\n`;
      csvContent += `Export Date,${data.metadata.exportDate || data.metadata.generatedAt}\n`;
      csvContent += `Total Records,${data.metadata.totalRecords}\n`;
      csvContent += `Generated By,${data.metadata.generatedBy || 'Social Listening System'}\n`;
      if (data.metadata.searchQuery) {
        csvContent += `Search Query,"${data.metadata.searchQuery}"\n`;
      }
      if (data.metadata.platform) {
        csvContent += `Platform,${data.metadata.platform}\n`;
      }
      if (data.metadata.keyword) {
        csvContent += `Keyword,"${data.metadata.keyword}"\n`;
      }
      csvContent += `\n`;
    }

    // Export generic data (new structure)
    if (data.data && data.data.length > 0) {
      const sectionTitle = data.title || 'Data Export';
      csvContent += `# ${sectionTitle}\n`;
      
      // Create header row from columns
      if (data.columns && data.columns.length > 0) {
        const headers = data.columns.map(col => col.label);
        csvContent += headers.join(',') + '\n';
        
        console.log('📋 CSV headers:', headers);
        console.log('📊 Data rows count:', data.data.length);
        
        // Export data rows
        data.data.forEach((item, index) => {
          const row = data.columns!.map(col => {
            let value = item[col.key];
            
            // Apply formatting if available
            if (col.format && typeof col.format === 'function') {
              value = col.format(value);
            }
            
            // Handle different data types
            if (col.type === 'string' && typeof value === 'string') {
              return `"${value.replace(/"/g, '""')}"`; // Escape quotes
            } else if (col.type === 'url' && value) {
              return `"${value}"`;
            } else if (value === null || value === undefined) {
              return '';
            } else {
              return value;
            }
          });
          csvContent += row.join(',') + '\n';
        });
      } else {
        // Fallback: export as key-value pairs
        csvContent += `Key,Value\n`;
        data.data.forEach((item, index) => {
          Object.entries(item).forEach(([key, value]) => {
            csvContent += `"${key}","${String(value).replace(/"/g, '""')}"\n`;
          });
        });
      }
      csvContent += '\n';
    }

    // Export content data (legacy structure)
    if (data.content && data.content.length > 0) {
      csvContent += `# Social Media Content\n`;
      csvContent += `ID,Platform,Content,Author,Username,Followers,Verified,Likes,Shares,Comments,Views,Total Engagement,Hashtags,Mentions,Published At,URL,Media Type,Sentiment Score,Sentiment Label,Reach,Viral,Language,Location\n`;
      
      data.content.forEach(item => {
        const row = [
          item.id,
          item.platform,
          `"${item.content.replace(/"/g, '""')}"`, // Escape quotes
          `"${item.author.name.replace(/"/g, '""')}"`,
          item.author.username,
          item.author.followers || 0,
          item.author.verified ? 'Yes' : 'No',
          item.engagement.likes,
          item.engagement.shares,
          item.engagement.comments,
          item.engagement.views,
          item.engagement.total,
          `"${item.hashtags.join('; ')}"`,
          `"${item.mentions.join('; ')}"`,
          item.publishedAt,
          item.url,
          item.media.type,
          item.sentiment.score,
          item.sentiment.label,
          item.reach.estimated,
          item.reach.viral ? 'Yes' : 'No',
          item.language,
          item.location || ''
        ];
        csvContent += row.join(',') + '\n';
      });
      csvContent += '\n';
    }

    // Export hashtag data
    if (data.hashtags && data.hashtags.length > 0) {
      csvContent += `# Hashtag Metrics\n`;
      csvContent += `Hashtag,Mentions,Platforms,Total Engagement,Likes,Shares,Comments,Views,Positive %,Negative %,Neutral %,Trend Direction,Trend Change,Reach,Viral,Last Seen\n`;
      
      data.hashtags.forEach(hashtag => {
        const row = [
          hashtag.hashtag,
          hashtag.count,
          `"${hashtag.platforms.join('; ')}"`,
          hashtag.engagement.total,
          hashtag.engagement.likes,
          hashtag.engagement.shares,
          hashtag.engagement.comments,
          hashtag.engagement.views,
          hashtag.sentiment.positive,
          hashtag.sentiment.negative,
          hashtag.sentiment.neutral,
          hashtag.trend.direction,
          hashtag.trend.change,
          hashtag.reach.estimated,
          hashtag.reach.viral ? 'Yes' : 'No',
          hashtag.lastSeen
        ];
        csvContent += row.join(',') + '\n';
      });
      csvContent += '\n';
    }

    // Export platform data
    if (data.platforms && data.platforms.length > 0) {
      csvContent += `# Platform Metrics\n`;
      csvContent += `Platform,Total Content,Total Engagement,Avg Engagement,Engagement Rate,Reach,Positive %,Negative %,Neutral %\n`;
      
      data.platforms.forEach(platform => {
        const row = [
          platform.platform,
          platform.totalContent,
          platform.totalEngagement,
          platform.avgEngagement.toFixed(2),
          platform.engagementRate.toFixed(2),
          platform.reach,
          platform.sentiment.positive,
          platform.sentiment.negative,
          platform.sentiment.neutral
        ];
        csvContent += row.join(',') + '\n';
      });
    }

    return new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  }

  // Export data to JSON format
  async exportToJSON(data: ExportData, options: ExportOptions): Promise<Blob> {
    const exportData = {
      ...data,
      exportOptions: options,
      generatedAt: new Date().toISOString()
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    return new Blob([jsonContent], { type: 'application/json' });
  }

  // Export data to PDF format
  async exportToPDF(data: ExportData, targetElement?: HTMLElement): Promise<void> {
    try {
      let canvas: HTMLCanvasElement;
      const captureScale = 2;
      
      if (targetElement && typeof window !== 'undefined') {
        console.log('📄 Starting PDF export (block-based pagination)...');

        // IMPORTANT: never mutate the live dashboard DOM for capture.
        // Instead, clone the target section into an off-screen sandbox so the UI
        // does not reflow/shift while exporting.
        const targetWidth = 800; // A4-friendly capture width
        let sandbox: HTMLDivElement | null = null;
        let clone: HTMLElement | null = null;

        try {
          sandbox = document.createElement('div');
          sandbox.style.position = 'fixed';
          sandbox.style.left = '-10000px';
          sandbox.style.top = '0';
          sandbox.style.width = `${targetWidth}px`;
          sandbox.style.background = '#ffffff';
          sandbox.style.pointerEvents = 'none';
          sandbox.style.opacity = '0';
          sandbox.style.zIndex = '-1';

          clone = targetElement.cloneNode(true) as HTMLElement;
          clone.classList.add('pdfExportMode');
          clone.style.width = `${targetWidth}px`;
          clone.style.maxWidth = 'none';
          clone.style.overflow = 'visible';

          sandbox.appendChild(clone);
          document.body.appendChild(sandbox);

          // Wait a tick so fonts/layouts in the clone settle.
          await new Promise(resolve => setTimeout(resolve, 250));

        // Create PDF upfront so we can paginate per-block.
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pageWidth = pdf.internal.pageSize.getWidth(); // 210mm
        const pageHeight = pdf.internal.pageSize.getHeight(); // 297mm
        const margin = 10;
        const availableWidth = pageWidth - (margin * 2);
        const availableHeight = pageHeight - (margin * 2);
        const pxToMm = 0.264583; // 96 DPI

        let cursorY = margin;

        const addCanvasToPdf = (blockCanvas: HTMLCanvasElement) => {
          const imgData = blockCanvas.toDataURL('image/png', 1.0);
          const imgWidthMm = blockCanvas.width * pxToMm;
          const imgHeightMm = blockCanvas.height * pxToMm;
          const widthScale = availableWidth / imgWidthMm;
          const scaledWidth = availableWidth;
          const scaledHeight = imgHeightMm * widthScale;

          // New page if it won't fit on current page
          if (cursorY !== margin && cursorY + scaledHeight > pageHeight - margin) {
            pdf.addPage();
            cursorY = margin;
          }

          // If it's taller than a full page, we must slice it (rare once we split by blocks).
          if (scaledHeight > availableHeight) {
            const mmPerPx = pxToMm * widthScale;
            const maxPageHeightPx = Math.floor(availableHeight / mmPerPx);
            let sourceY = 0;
            let pageIndex = 0;

            while (sourceY < blockCanvas.height - 1) {
              const sliceHeight = Math.min(maxPageHeightPx, blockCanvas.height - sourceY);
              if (pageIndex > 0 || cursorY !== margin) {
                pdf.addPage();
                cursorY = margin;
              }

              const sliceCanvas = document.createElement('canvas');
              const sliceCtx = sliceCanvas.getContext('2d');
              if (!sliceCtx) throw new Error('Could not get canvas context');
              sliceCanvas.width = blockCanvas.width;
              sliceCanvas.height = sliceHeight;
              sliceCtx.drawImage(
                blockCanvas,
                0,
                sourceY,
                blockCanvas.width,
                sliceHeight,
                0,
                0,
                blockCanvas.width,
                sliceHeight
              );

              const sliceImgData = sliceCanvas.toDataURL('image/png', 1.0);
              const sliceScaledHeight = sliceHeight * mmPerPx;
              pdf.addImage(sliceImgData, 'PNG', margin, cursorY, scaledWidth, sliceScaledHeight);
              sourceY += sliceHeight;
              pageIndex += 1;
            }
            cursorY = margin; // next block starts on fresh page after slicing
            return;
          }

          pdf.addImage(imgData, 'PNG', margin, cursorY, scaledWidth, scaledHeight);
          cursorY += scaledHeight + 4; // small gap between blocks
        };

        const captureAndAdd = async (el: HTMLElement, depth = 0): Promise<void> => {
          // Skip hidden elements
          const style = window.getComputedStyle(el);
          if (style.display === 'none' || style.visibility === 'hidden') return;

          // Capture this element
          const blockCanvas = await html2canvas(el, {
            scale: captureScale,
            useCORS: true,
            allowTaint: true,
            backgroundColor: '#ffffff',
            logging: false,
            scrollX: 0,
            scrollY: 0,
            windowWidth: targetWidth
          });

          // If the captured block doesn't fit on a page, recursively split into children blocks.
          const imgWidthMm = blockCanvas.width * pxToMm;
          const imgHeightMm = blockCanvas.height * pxToMm;
          const widthScale = availableWidth / imgWidthMm;
          const scaledHeight = imgHeightMm * widthScale;

          if (scaledHeight > availableHeight && depth < 2) {
            const childEls = Array.from(el.children).filter(
              (c): c is HTMLElement => c instanceof HTMLElement
            );
            if (childEls.length > 1) {
              for (const child of childEls) {
                await captureAndAdd(child, depth + 1);
              }
              return;
            }
          }

          addCanvasToPdf(blockCanvas);
        };

        // Capture direct children in order; this avoids breaking mid-graph.
        const topLevelBlocks = Array.from(clone.children).filter(
          (c): c is HTMLElement => c instanceof HTMLElement
        );
        for (const block of topLevelBlocks) {
          await captureAndAdd(block, 0);
        }

        const filename = this.generateFilename(data, { format: 'pdf' });
        console.log('💾 Saving PDF:', filename);
        pdf.save(filename);
        console.log('✅ PDF export completed successfully');
        return;
        } finally {
          if (sandbox && sandbox.parentNode) {
            sandbox.parentNode.removeChild(sandbox);
          }
        }
      } else if (typeof window !== 'undefined') {
        // Create a PDF from data (fallback)
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        
        // Add title
        pdf.setFontSize(20);
        pdf.text('Social Listening Report', pageWidth / 2, 20, { align: 'center' });
        
        // Add metadata
        if (data.metadata) {
          pdf.setFontSize(12);
          pdf.text(`Generated: ${new Date(data.metadata.generatedAt || Date.now()).toLocaleString()}`, 20, 40);
          pdf.text(`Total Records: ${data.metadata.totalRecords}`, 20, 50);
        }
        
        // Add content summary
        let yPosition = 70;
        pdf.setFontSize(14);
        pdf.text('Data Summary:', 20, yPosition);
        yPosition += 10;
        
        pdf.setFontSize(10);
        if (data.data && data.data.length > 0) {
          pdf.text(`• ${data.data.length} search results`, 20, yPosition);
          yPosition += 8;
        }
        if (data.content && data.content.length > 0) {
          pdf.text(`• ${data.content.length} social media posts`, 20, yPosition);
          yPosition += 8;
        }
        if (data.hashtags && data.hashtags.length > 0) {
          pdf.text(`• ${data.hashtags.length} hashtag metrics`, 20, yPosition);
          yPosition += 8;
        }
        if (data.platforms && data.platforms.length > 0) {
          pdf.text(`• ${data.platforms.length} platform metrics`, 20, yPosition);
          yPosition += 8;
        }
        
        const filename = this.generateFilename(data, { format: 'pdf' });
        pdf.save(filename);
        return;
      } else {
        // Server-side or no browser environment - fallback to CSV
        console.warn('PDF export not available in server environment, falling back to CSV');
        const csvBlob = await this.exportToCSV(data, { 
          format: 'csv', 
          includeMetadata: true 
        });
        const filename = this.generateFilename(data, { format: 'csv' });
        this.downloadFile(csvBlob, filename);
        return;
      }
      
      // Convert canvas to PDF with full page view and multi-page support
      const imgData = canvas.toDataURL('image/png', 1.0);
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth(); // 210mm
      const pageHeight = pdf.internal.pageSize.getHeight(); // 297mm
      
      // Use full page width with minimal margins (10mm each side)
      const margin = 10; // 10mm margin on all sides
      const availableWidth = pageWidth - (margin * 2); // 190mm
      const availableHeight = pageHeight - (margin * 2); // 277mm
      
      // Calculate dimensions
      // Convert canvas pixels to mm (assuming 96 DPI: 1px = 0.264583mm)
      const pxToMm = 0.264583;
      const imgWidthMm = canvas.width * pxToMm;
      const imgHeightMm = canvas.height * pxToMm;
      
      // Calculate scale to fit full page width
      const widthScale = availableWidth / imgWidthMm;
      const scaledWidth = availableWidth; // Use full available width
      const scaledHeight = imgHeightMm * widthScale; // Maintain aspect ratio
      
      console.log('📐 PDF dimensions:', {
        pageWidth,
        pageHeight,
        availableWidth,
        availableHeight,
        imgWidthMm,
        imgHeightMm,
        scaledWidth,
        scaledHeight,
        pagesNeeded: Math.ceil(scaledHeight / availableHeight)
      });
      
      // Calculate number of pages needed
      const pagesNeeded = Math.ceil(scaledHeight / availableHeight);
      
      if (pagesNeeded === 1) {
        // Single page - use full width, center vertically if content is smaller
        const x = margin;
        const y = scaledHeight < availableHeight 
          ? margin + (availableHeight - scaledHeight) / 2 
          : margin;
        pdf.addImage(imgData, 'PNG', x, y, scaledWidth, scaledHeight);
      } else {
        // Multi-page - split content across pages (fallback path when no targetElement provided).
        const mmPerPx = pxToMm * widthScale; // because we fit-to-width
        const maxPageHeightPx = Math.floor(availableHeight / mmPerPx);
        let pageIndex = 0;
        let sourceY = 0;
        while (sourceY < canvas.height - 1) {
          const breakY = Math.min(canvas.height, Math.max(sourceY + 1, sourceY + maxPageHeightPx));
          const sourceHeight = breakY - sourceY;

          if (pageIndex > 0) pdf.addPage();

          const pageCanvas = document.createElement('canvas');
          const pageCtx = pageCanvas.getContext('2d');
          if (!pageCtx) throw new Error('Could not get canvas context');

          pageCanvas.width = canvas.width;
          pageCanvas.height = sourceHeight;
          pageCtx.drawImage(
            canvas,
            0,
            sourceY,
            canvas.width,
            sourceHeight,
            0,
            0,
            canvas.width,
            sourceHeight
          );

          const pageImgData = pageCanvas.toDataURL('image/png', 1.0);
          const pageScaledHeight = sourceHeight * mmPerPx;
          pdf.addImage(pageImgData, 'PNG', margin, margin, scaledWidth, pageScaledHeight);

          console.log(`📄 Added page ${pageIndex + 1}/${pagesNeeded}`, {
            sourceY,
            breakY,
            sourceHeight,
            maxPageHeightPx,
            pageScaledHeight
          });

          sourceY = breakY;
          pageIndex += 1;
        }
      }
      
      const filename = this.generateFilename(data, { format: 'pdf' });
      console.log('💾 Saving PDF:', filename);
      pdf.save(filename);
      console.log('✅ PDF export completed successfully');
      
    } catch (error) {
      console.error('PDF export failed:', error);
      
      // Fallback to CSV export
      try {
        const csvBlob = await this.exportToCSV(data, { 
          format: 'csv', 
          includeMetadata: true 
        });
        const filename = this.generateFilename(data, { format: 'csv' });
        this.downloadFile(csvBlob, filename);
        alert('PDF export failed. CSV file has been downloaded instead.');
      } catch (fallbackError) {
        console.error('Fallback export also failed:', fallbackError);
        alert('Export failed. Please try again.');
      }
    }
  }

  // Export data to XLS format
  async exportToXLS(data: ExportData): Promise<void> {
    // Export as CSV with .xls extension (Excel can open CSV files)
    const csvBlob = await this.exportToCSV(data, { 
      format: 'csv', 
      includeMetadata: true 
    });
    const filename = this.generateFilename(data, { format: 'xlsx' });
    this.downloadFile(csvBlob, filename);
  }

  // Main export function
  async exportData(data: ExportData, options: ExportOptions): Promise<Blob> {
    switch (options.format) {
      case 'csv':
        return this.exportToCSV(data, options);
      case 'json':
        return this.exportToJSON(data, options);
      case 'pdf':
        await this.exportToPDF(data);
        return new Blob(['PDF exported'], { type: 'text/plain' });
      case 'xlsx':
        await this.exportToXLS(data);
        return new Blob(['XLS exported'], { type: 'text/plain' });
      default:
        throw new Error(`Unsupported export format: ${options.format}`);
    }
  }

  // Download file helper
  downloadFile(blob: Blob, filename: string): void {
    console.log('💾 downloadFile called with:', { blob, filename, blobSize: blob.size });
    
    if (typeof window === 'undefined') {
      console.warn('Download not available in server environment');
      return;
    }
    
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    console.log('🔗 Created download link:', { href: link.href, download: link.download });
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    console.log('✅ Download completed');
  }

  // Generate filename based on data and options
  generateFilename(data: ExportData, options: ExportOptions): string {
    const timestamp = new Date().toISOString().split('T')[0];
    const extension = options.format === 'xlsx' ? 'xls' : options.format;
    
    // Determine data type based on available data
    let dataType = 'data';
    if (data.content) {
      dataType = 'content';
    } else if (data.hashtags) {
      dataType = 'hashtags';
    } else if (data.platforms) {
      dataType = 'platforms';
    } else if (data.data) {
      dataType = 'search-results';
    }
    
    // Add section info if available
    const section = data.metadata?.section ? `-${data.metadata.section.toLowerCase().replace(/\s+/g, '-')}` : '';
    
    // Add platform info if available
    const platform = data.metadata?.platform ? `-${data.metadata.platform}` : '';
    
    return `social-listening${section}${platform}-${dataType}-${timestamp}.${extension}`;
  }
}

export const exportService = new ExportService();
